export const STATES = [
  { value: "1", label: "Alabama" },
  { value: "2", label: "Alaska" },
  { value: "3", label: "Arizona" },
  { value: "4", label: "Arkansas" },
  { value: "5", label: "California" },
  { value: "6", label: "North Carolina" },
  { value: "7", label: "South Carolina" },
  { value: "8", label: "Colorado" },
  { value: "9", label: "Connecticut" },
  { value: "10", label: "North Dakota" },
  { value: "11", label: "South Dakota" },
  { value: "12", label: "Delaware" },
  { value: "13", label: "Florida" },
  { value: "14", label: "Georgia" },
  { value: "15", label: "Hawaii" },
  { value: "16", label: "Idaho" },
  { value: "17", label: "Illinois" },
  { value: "18", label: "Indiana" },
  { value: "19", label: "Iowa" },
  { value: "20", label: "Kansas" },
  { value: "21", label: "Kentucky" },
  { value: "22", label: "Luisiana" },
  { value: "23", label: "Maine" },
  { value: "24", label: "Maryland" },
  { value: "25", label: "Massachusetts" },
  { value: "26", label: "Míchigan" },
  { value: "27", label: "Minnesota" },
  { value: "", label: "Mississipi" },
  { value: "", label: "Misouri" },
  { value: "", label: "Montana" },
  { value: "", label: "Nebraska" },
  { value: "", label: "Nevada" },
  { value: "", label: "New Jersey" },
  { value: "", label: "New York" },
  { value: "", label: "New Hampshire" },
  { value: "", label: "New México" },
  { value: "", label: "Ohio" },
  { value: "", label: "Oklahoma" },
  { value: "", label: "Oregon" },
  { value: "", label: "Pennsylvania" },
  { value: "", label: "Rhode Island" },
  { value: "", label: "Tennessee" },
  { value: "", label: "Texas" },
  { value: "", label: "Utah" },
  { value: "", label: "Vermont" },
  { value: "", label: "Virginia" },
  { value: "", label: "West Virginia" },
  { value: "", label: "Washington" },
  { value: "", label: "Wisconsin" },
  { value: "", label: "Wyoming" },
];
